services:
  db:
    image: mysql:8
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rastrofacil
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mailhog:
    image: ghcr.io/mailhog/mailhog:v1.0.1-arm64
    ports:
      - "8025:8025"
